export default {
  // nav
  OPEN_NAV: 'OPEN_NAV',
  CLOSE_NAV: 'CLOSE_NAV',
  TOGGLE_NAV: 'TOGGLE_NAV',

  // posts
  CREATE_POST: 'CREATE_POST',
  CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
  EDIT_POST: 'EDIT_POST',
  EDIT_POST_SUCCESS: 'EDIT_POST_SUCCESS',
  RETRIEVE_POST_SUCCESS: 'RETRIEVE_POST_SUCCESS',
  RETRIEVE_POST: 'RETRIEVE_POST',
  RETRIEVE_ALL_POSTS_SUCCESS: 'RETRIEVE_ALL_POSTS_SUCCESS',
  RETRIEVE_AUTHOR_POSTS: 'RETRIEVE_AUTHOR_POSTS',
  RETRIEVE_AUTHOR_POSTS_SUCCESS: 'RETRIEVE_AUTHOR_POSTS_SUCCESS',

  // auth
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',

  // profile
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  RETRIEVE_PROFILE: 'RETRIEVE_PROFILE',
  RETRIEVE_PROFILE_SUCCESS: 'RETRIEVE_PROFILE_SUCCESS',
  FOLLOW_PROFILE: 'FOLLOW_PROFILE',
  FOLLOW_PROFILE_SUCCESS: 'FOLLOW_PROFILE_SUCCESS',
  UNFOLLOW_PROFILE: 'UNFOLLOW_PROFILE',
  UNFOLLOW_PROFILE_SUCCESS: 'UNFOLLOW_PROFILE_SUCCESS'
}
